global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infra'
    static_configs:
      - targets: ['node-exporter:9100','192.168.1.20:9100']